# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Charybdis'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["charybdis_left","charybdis_right"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      alphas: '["qwerty"]'
      kconfig: '["CONFIG_BT_CTLR_TX_PWR_PLUS_8=y\nCONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y\nCONFIG_ZMK_EXT_POWER=y\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000\nCONFIG_SPI=y\nCONFIG_INPUT=y\nCONFIG_ZMK_MOUSE=y\nCONFIG_PMW3610=y\nCONFIG_ZMK_MOUSE=y\nCONFIG_MOUSE_LAYER_INDEX=3\nCONFIG_MOUSE_LAYER_ACTIVE_MS=750"]'
